COURSE_ACTS(COURSE_BOB, _(" 1 NAVY SANTA BREZAURY"),
       _("WILL YOU SWITCH CHEAP WITH THE KEEPOLE?"), _("THE RED DEVIL") , _("RIGHT-CLICK AND SELECT 『AWARE』"),
       _("RESPAWN ON BOB-OMB ISLAND")     , _("END OF THE OPERA TOURNAMENT") , _("THROUGH THE TINY CAVE"))

COURSE_ACTS(COURSE_WF, _(" 2 WORST-SAFE WAY TO WATERFALL"),
       _("NO THANKS, POOR BOY")           , _("NOT COOL!")                     , _("THE RED STAR"),
       _("RULES, PLEASE READ")            , _("AD DEMAND AMPS?")               , _("STUNNED AND FURYFUL"))

COURSE_ACTS(COURSE_JRB, _(" 3 ICE TILL TO BECOME A GOD"),
       _("THE STEP BY STEP GUIDE")        , _("IT'S A LONG, LONELY ROAD")      , _("STEP 11: CASTLE 2"),
       _("STEP ON EIGHT STAR!")           , _("YOU ARE AN EARTHKNIGHT.")       , _("JUMP ON THE SECOND RING!"))

COURSE_ACTS(COURSE_CCM, _(" 4 SMALL TALL TEN HASH"),
       _("GO ON SNOWS TO OBSERVATE THE WORLD"), _("BE A SKYGOGER, FORIEST ONI SHALL"), _("PRESS RELEASE"),
       _("CARE IN THE SUNSHINE PARAGRAPH"), _("GO ON TINY METAL QUARTERS")     , _("SHOCKING QUICK STEPS"))

COURSE_ACTS(COURSE_BBH, _(" 5 ICE CAPACITALS FORT ON"),
       _("BOB-OMB, THE RACOON KING")      , _("BEYOND TRANSLATED CHAPTER")     , _("THE LONG NIGHT..."),
       _("SCALE? EMPLOYEER!")             , _("A SECRET OF KOTON!")            , _("DEFINITELY CONDATED"))

COURSE_ACTS(COURSE_HMC, _(" 6 SALE RAINBOW LOST FOR REVENGE"),
       _("THROUGH THE SMALL ANCIENT BOMB!"), _("SLIP SKIRL IN THE SKY")        , _("BOWSER BIGFOO"),
       _("BIG BOB-OMB! WATCH FOR ROBBIE!"), _("BE RENDERING STEAM LAND")       , _("ELEVATE ROLLING BATTLE FOR BOWSER"))

COURSE_ACTS(COURSE_LLL, _(" 7 SWITCHBORO ADVISORY"),
       _("GRAND PRIZE ON FOR BEING EARLY"), _("BEAT THE BULLY")                , _("BOTH OF YOU A RUNAWAY!"),
       _("FROSTY TURBO IN THE TOWN")      , _("MONTHLY AND LUNCH SPECIAL!")    , _("LOCKE THE PYRAMID"))

COURSE_ACTS(COURSE_SSL, _(" 8 IN THE LAND OF TRAP AND DAMAGE"),
       _("ODORIER BROS.")                 , _("PREPARE TO PLAYAN IWO")         , _("QUICK, DIRTY WORK!"),
       _("SECRET OF WIMMING IN THE CAGE") , _("19 SCATTERED BACKGROUNDS")      , _("CAPS ON THE TOP OF THE TOWER"))

COURSE_ACTS(COURSE_DDD, _(" 9 THE LUNATIC VALLEY"),
       _("RIDE ARTICULATED TO THE NOSE!") , _("A BUG! BIG TROUBLE")            , _("HARDER STORM LOCATION"),
       _("COUNTERSINK IS CURVED ON")      , _("HE'S ONLY A FRIEND!")           , _("AND POWER SWORDS DISCARD"))

COURSE_ACTS(COURSE_SL, _("10 BRIDGE, MICHIGAN"),
       _("CHIP CHIP! BUILD TOBIN'S PLATFORM"), _("WELFARE, DISCRIMINATION, AND THE WAR ON WOMEN"), _("SHOCKING MERCULIVE CLIMATE"),
       _("THE CAVERN IS BACK")            , _("COURSE OF THE OCEAN")           , _("BELOW! VIDEO GAME COMEDY BUST!"))

COURSE_ACTS(COURSE_WDW, _("9WD AWARD WINNERS' COSTL"),
       _("ELEANOR'S SECRET CAMO")         , _("PULL UP ON VANISHIMERA")        , _("MODEING THROUGH THE SWORDBEATS"),
       _("WATCH FOR JUMP SHOOT")          , _("METAL JACK COINS!!")            , _("TAKE A SLUT"))

COURSE_ACTS(COURSE_TTM, _("12 SIZY ASSAULT THE EAGLE TRIBAL GUARDS"),
       _("YUREA")                         , _("INSTAGRAM'S RED PERIOD")        , _("TO THEE MAY SHE BELLOW?"),
	   _("3,590 LB WARD WHEEL WHEEL WITH STRAIGHT LONELY TOPOLOGY"), _("CAN IT MOVE ME?"), _("DEFINE! DIE NEXT TIME!"))

COURSE_ACTS(COURSE_THI, _("13 HACK DIVINE"),
       _("BIBIT!")                        , _("ARGOK'S RESISTOR?")            , _("THE BIG BULL-ARRIED BULL CORNER"),
       _("EVERY QUISFLEX CROSS GOOD INTO BAD COIN"), _("YOU'LL BE A INTO MARIO"), _("HITLERS!!"))

COURSE_ACTS(COURSE_TTC, _("14 AWESOME WET ANALYST"),
       _("WORK IN THE DISCHARGE STAR")    , _("RATINGS DUE THIS SUMMER")       , _("ZOWIE INTERACTIVE, INC."),
       _("THE STEAM MAGNIFIER!")          , _("BETTER CLIMBING UNDER THE STARS"), _("SUBMISS TO THE ANCIENT WHOM"))

COURSE_ACTS(COURSE_RR, _("15 UPPER LOWER BIG BENINS"),
       _("BLAST AWAY THE HIGH PRESSOFANE"), _("WHIPS CONTAIN THREE WHISPERS")  , _("CONSIDER THE TIME: 3:30 PM."),
       _("TOWN OF THE REVENGE'S")         , _("ARE CRIMINALS TARGET CROSSING THE DARK SKY"), _("CAP'N"))

SECRET_STAR(COURSE_BITDW, _("   AM THROUGH THE WINGING IN THE MIDDLE"))
SECRET_STAR(COURSE_BITFS, _("   BOWSER'S BIG STAR-CROSSING STATION"))
SECRET_STAR(COURSE_BITS, _("   IN THE SKY HIGH MERCA FOR FAST, INVISIBLE POKER BLOCK"))
SECRET_STAR(COURSE_PSS, _("   SECRET VIEW FROM THE 25 STREAMED ILLUMINATED FLOWER"))
SECRET_STAR(COURSE_COTMC, _("   REALLY-GUMMY-WILD THIEVOS"))
SECRET_STAR(COURSE_TOTWC, _("   AUTOMATIC WING DRAWING RETICLE"))
SECRET_STAR(COURSE_VCUTM, _("   『ELEVATOR SKY SLIFT』"))
SECRET_STAR(COURSE_WMOTR, _("   RAINBOW RACE IN THE RAINBOW"))
SECRET_STAR(COURSE_SA, _("   ICE FLY ISLAND"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("THE 『CCC』 RESTAINS OUTGOING ATTACKS EVEN IN INACCESSIBLE DANGER STAR WORLD STAGES."))

EXTRA_TEXT(0, _("ONE MORE TO CLOSE THE COURSE'S BLOG!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
